## RNN : Recural Neural Network

RNN >> is Neural network which is designed for sequential data.

Sequential data>> text,audio,time series,DNA sequence.

In [128]:
# ANN >> work on Structured and tabular data,images.
#CNN >>

In [129]:
# applications where use RNN:
# 1) sentiment analysis
# 2) chatbot
# 3) langauge translataion
# 4) word prediction
# 5) stock market prediction
# 6) weather forcasting
# 7) alexa /siri  Speech recognition
# 8) Text generation


In [130]:
# RNN -> It is Neural Network with Memory.

In [131]:
# Eg. 1 ) Many to one :

In [132]:
# iNput >> 1,2,3,4
#output >> 5

In [133]:
import numpy as np
import pandas as pd
from tensorflow.keras.layers import Dense,SimpleRNN
from tensorflow.keras.models import Sequential

In [134]:
# we are going to work on User data:

In [135]:
X= np.array([[1,2,3,4]])
y= np.array([5])

In [136]:
#Step 1 : input reshape

In [137]:
# cnn >> 1,256,256,3
# RNN >> 1,4,1 >> it means 1 3D aray that have 4 rows and  1 column. because it is many to one 

In [138]:
X_new= X.reshape((1,4,1))

In [139]:
X_new

array([[[1],
        [2],
        [3],
        [4]]])

In [140]:
y

array([5])

In [141]:
# scaling : but here scaling not required.

In [142]:
# step 2 : Model Training.

In [143]:
 model = Sequential([
       SimpleRNN(10,activation='relu',input_shape=(4,1)), #sirst input layer & 10 is no.of units.
       Dense(1)                                          # here no need activation func.
  ])
     

d:\ITVedant\itv-AiML_projects\Restaurant-Reviews-Predictions-With-RNN_Lstm\Project_env\lib\site-packages\keras\src\layers\rnn\rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [144]:
#here we use loss = mse >> becuz it is regression or countinued data example. 
#& NO need accuracy in this example..becoz here only single o/p
model.compile(optimizer='adam',loss='mse')

In [145]:
model.fit(X_new,y,epochs=193)

Epoch 1/193


1/1 ━━━━━━━━━━━━━━━━━━━━ 3s 3s/step - loss: 1.2942
Epoch 2/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step - loss: 1.1429
Epoch 3/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 184ms/step - loss: 1.0020
Epoch 4/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 138ms/step - loss: 0.8716
Epoch 5/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step - loss: 0.7516
Epoch 6/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 201ms/step - loss: 0.6419
Epoch 7/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 283ms/step - loss: 0.5424
Epoch 8/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step - loss: 0.4528
Epoch 9/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 125ms/step - loss: 0.3729
Epoch 10/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 125ms/step - loss: 0.3024
Epoch 11/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 243ms/step - loss: 0.2408
Epoch 12/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step - loss: 0.1878
Epoch 13/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step - loss: 0.1428
Epoch 14/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 163ms/step - loss: 0.1052
Epoch 15/193
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 130ms/step - loss: 0.0746
Epoch 16/193
1/1 ━━

In [146]:
model.predict(X_new)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 363ms/step


array([[5.000046]], dtype=float32)

In [147]:
# NOw work on New User data :

In [148]:
a=np.array([[6,7,8,9]])

In [149]:
#  : Reshape the input

In [150]:
a_new=a.reshape((1,4,1))

In [151]:
model.predict(a_new)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 105ms/step


array([[10.574869]], dtype=float32)

In [152]:
# Pre Data work

## Case Study -1 Restaurant reviews Predictions 

In [153]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, SimpleRNN, LSTM, GRU, Dense
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
import numpy as np
import pandas as pd

In [154]:
# Step 1. Read data:

In [222]:
df=pd.read_csv('r_data.tsv',delimiter='\t')

In [223]:
df

,Review,Liked
0,Wow... Loved this place.,1
1,Crust is not good.,0
2,Not tasty and the texture was just nasty.,0
3,Stopped by during the late May bank holiday of...,1
4,The selection on the menu was great and so wer...,1
...,...,...
1390,not bad,1
1391,bad tase,0
1392,bad food,0
1393,bad taste,0


In [224]:
df.shape

(1395, 2)

In [225]:
# Step 2. Data Cleaning :

In [226]:
df.isnull().sum()

Review    0
Liked     0
dtype: int64

In [227]:
df.dtypes

Review    object
Liked      int64
dtype: object

In [228]:
# Step 3.Text Preprocessing : 

# Lowercase,special characters,digit stopwords steming etc we have to do in preprocess

In [229]:
#NLP - NLTK packages

In [230]:
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import PorterStemmer
import re


In [231]:
# let create stopwords list first to future:

s_list=stopwords.words('english')

In [232]:
#which u want word that remove from stopword.
s_list.remove('not')

In [233]:
len(s_list)

197

In [234]:
# then iterate all review one by one from list to array for train and understand.

In [235]:
df['Review']

0                                Wow... Loved this place.
1                                      Crust is not good.
2               Not tasty and the texture was just nasty.
3       Stopped by during the late May bank holiday of...
4       The selection on the menu was great and so wer...
                              ...                        
1390                                              not bad
1391                                             bad tase
1392                                             bad food
1393                                            bad taste
1394                                          bad quality
Name: Review, Length: 1395, dtype: object

In [236]:
for i in df['Review']:
    print(i)

Wow... Loved this place.
Crust is not good.
Not tasty and the texture was just nasty.
Stopped by during the late May bank holiday off Rick Steve recommendation and loved it.
The selection on the menu was great and so were the prices.
Now I am getting angry and I want my damn pho.
Honeslty it didn't taste THAT fresh.)
The potatoes were like rubber and you could tell they had been made up ahead of time being kept under a warmer.
The fries were great too.
A great touch.
Service was very prompt.
Would not go back.
The cashier had no care what so ever on what I had to say it still ended up being wayyy overpriced.
I tried the Cape Cod ravoli, chicken, with cranberry...mmmm!
I was disgusted because I was pretty sure that was human hair.
I was shocked because no signs indicate cash only.
Highly recommended.
Waitress was a little slow in service.
This place is not worth your time, let alone Vegas.
did not like at all.
The Burrittos Blah!
The food, amazing.
Service is also cute.
I could care les

In [237]:
# now use nlp concepts preprocessing steps:

In [238]:
corpus=[]
for i in df['Review']:
    mystr=i.lower()          #for lowercase convert 1st step.
    newstr=re.sub(r'[^a-zA-Z\s]','',mystr) # remove special character's/digit.
    list1=word_tokenize(newstr)  # use tokenizer for split each word.
    list2=[ i for i in list1 if i not in s_list]   # use this for remove stopwords.
    ps=PorterStemmer()                          # Use Stemming (last word removing unnecesry.
    list3=[ps.stem(i) for i in list2] #stemming
    final=' '.join(list3)         # for convert list in to  string structure.
    corpus.append(final)

In [239]:
corpus

['wow love place',
 'crust not good',
 'not tasti textur nasti',
 'stop late may bank holiday rick steve recommend love',
 'select menu great price',
 'get angri want damn pho',
 'honeslti didnt tast fresh',
 'potato like rubber could tell made ahead time kept warmer',
 'fri great',
 'great touch',
 'servic prompt',
 'would not go back',
 'cashier care ever say still end wayyy overpr',
 'tri cape cod ravoli chicken cranberrymmmm',
 'disgust pretti sure human hair',
 'shock sign indic cash',
 'highli recommend',
 'waitress littl slow servic',
 'place not worth time let alon vega',
 'not like',
 'burritto blah',
 'food amaz',
 'servic also cute',
 'could care less interior beauti',
 'perform',
 'that rightth red velvet cakeohhh stuff good',
 'never brought salad ask',
 'hole wall great mexican street taco friendli staff',
 'took hour get food tabl restaur food luke warm sever run around like total overwhelm',
 'worst salmon sashimi',
 'also combo like burger fri beer decent deal',
 'like

In [240]:
# Step 4. Vectorization (like encoding and standardCaling):

In [241]:
# Vectorization : It converts long text data into numeric form.

# text >> numric form

# Vectorizar Type :
# 1) countvectorizar
# 2) Tokenizer(keras)
# 3) TF-ID vectorizer



In [242]:
# 1.) Count_Vectorizar :(it count the words..and it is available in sk-learn.)

In [243]:
# it is use for encoding or text convert in numeric for training .

In [244]:
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer()

X = cv.fit_transform(corpus).toarray()
y= df['Liked']

In [245]:
X.shape  # in that here whatever uniqe word u have that much column we'll have.

(1395, 1613)

In [246]:
# Exlanation of above work:

#  eg.               Hi    how are  you good   by tc
# Hi how are you     1     1    1    1   0     0  0 
# are you good       0     0    1    1    1    0  0
# by by tc           0     0    0    0    0    2  1


In [247]:
y

0       1
1       0
2       0
3       1
4       1
       ..
1390    1
1391    0
1392    0
1393    0
1394    0
Name: Liked, Length: 1395, dtype: int64

In [248]:
X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(1395, 1613))

In [249]:
# Curse of dimensionality >> bcoz more feature it will confused 
# >> so we use best features only. so we use below
cv.get_feature_names_out()

array(['absolut', 'absolutley', 'accid', ..., 'yum', 'yummi', 'zero'],
      shape=(1613,), dtype=object)

In [250]:
len(cv.get_feature_names_out())

1613

In [251]:
X_df = pd.DataFrame(X,columns=cv.get_feature_names_out())

In [252]:
X_df   # here we create the 1612 columns for each uniqe word and with its count.

,absolut,absolutley,accid,accommod,accomod,accordingli,account,ach,acknowledg,across,...,yelper,yet,youd,youll,your,yucki,yukon,yum,yummi,zero
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1390,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1391,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1392,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1393,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0


In [253]:
# Step 5. Cross validation : (train_test_split)

In [254]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test =train_test_split(X_df,y,test_size=0.2,random_state=42)

In [255]:
# Step 6. Model Training :

In [256]:
# models for train :

# 1) naive bayes : It use for calculate probavlity of event.
#                 Multinominal bayes >> use for text data.

In [257]:
from sklearn.naive_bayes import MultinomialNB

clf=MultinomialNB()
clf.fit(X_train,y_train)

,alpha,1.0
,force_alpha,True
,fit_prior,True
,class_prior,None


In [258]:
clf.score(X_test,y_test)

0.8172043010752689

In [259]:
# so above MultinomialNB model we got 80% accuracy on this model.

In [260]:
# 2) Logostic Regression model :it use for descret data and calculate the  probablity.

In [261]:
from sklearn.linear_model import LogisticRegression

clf1=LogisticRegression()
clf1.fit(X_train,y_train)

,penalty,'l2'
,dual,False
,tol,0.0001
,C,1.0
,fit_intercept,True
,intercept_scaling,1
,class_weight,None
,random_state,None
,solver,'lbfgs'
,max_iter,100
,multi_class,'deprecated'


In [262]:
clf1.score(X_test,y_test)

0.8028673835125448

In [263]:
# for logistic regression we got 83% accuracy. so we use logistic regresion model.
# final model >> clf1 >> logistic regression 

In [264]:
# Step 7. Prediction and Metrics :

In [265]:
y_pred= clf1.predict(X_test)

In [266]:
from sklearn.metrics import confusion_matrix,classification_report

In [267]:
print(confusion_matrix(y_test,y_pred))

[[102  27]
 [ 28 122]]


In [268]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.78      0.79      0.79       129
           1       0.82      0.81      0.82       150

    accuracy                           0.80       279
   macro avg       0.80      0.80      0.80       279
weighted avg       0.80      0.80      0.80       279



In [269]:
# Step 8. Predict New Review with model :

In [270]:
a= 'good taste'

In [271]:
# convert in list or array :

a= np.array(['not good taste'])

In [272]:
a_new =cv.transform(a).toarray()

In [273]:
a_new.shape

(1, 1613)

In [274]:
clf1.predict(a_new)

d:\ITVedant\itv-AiML_projects\Restaurant-Reviews-Predictions-With-RNN_Lstm\Project_env\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array([0])

In [275]:
# So we got 1 means good . but its not supprt to not etc.

## RNN LSTM MODEL :

In [276]:
# Solustion for simple Model >> RNN >>LSTM/GRU.
# next advance is >> transformer.

In [277]:
# Step 1. cleaning and text preprocessing :

In [278]:
df['Review']=corpus

In [279]:
# here clean the dataframe by using corpus assign.

In [280]:
df

,Review,Liked
0,wow love place,1
1,crust not good,0
2,not tasti textur nasti,0
3,stop late may bank holiday rick steve recommen...,1
4,select menu great price,1
...,...,...
1390,not bad,1
1391,bad tase,0
1392,bad food,0
1393,bad tast,0


In [281]:
# Here we use Tokenizer instead of vectorization in LSTM RNN to convert in numeric.
# because vectorisation is us in ML and Tokenizer use in DL-RNN,CNN ,its same to work.

In [282]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [283]:
max_words=5000
max_len=100

In [284]:
tk= Tokenizer(num_words=max_words)
tk.fit_on_texts(df['Review'])

In [285]:
# for deployment we use here pickle (to convert in numeric) :
import pickle
with open('tokenizer.pk1','wb') as f:                   #wb meanse convert in binary form
    pickle.dump(tk,f)

In [286]:
# here bcoz of pickle for deployment we use mysql,github,python 3.10,vs code.

In [287]:
# now  create  x,y. with pading:

In [288]:
X=tk.texts_to_sequences(df['Review'])

In [289]:
X=pad_sequences(X,maxlen=max_len)  # prepading (so here before rows ,cols 0 will be 
                                   #  on blanks spot.)

In [290]:
X.shape

(1395, 100)

In [291]:
X

array([[  0,   0,   0, ..., 354,  14,   3],
       [  0,   0,   0, ..., 489,   2,   5],
       [  0,   0,   0, ...,  34, 355,  82],
       ...,
       [  0,   0,   0, ...,   0,  28,   1],
       [  0,   0,   0, ...,   0,  28,  35],
       [  0,   0,   0, ...,   0,  28,  80]],
      shape=(1395, 100), dtype=int32)

In [292]:
y= df['Liked']

In [293]:
y

0       1
1       0
2       0
3       1
4       1
       ..
1390    1
1391    0
1392    0
1393    0
1394    0
Name: Liked, Length: 1395, dtype: int64

In [294]:
# step 2. Train test split :

In [295]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test =train_test_split(X,y,test_size=0.2,random_state=42)

In [296]:
# step 3. Model Train with LSTM :

In [297]:
# wow love place >> [0,0,0,.....354,14, 3]
# LSTM cannot understand raw integers directly in a meaningful way.

# why embedding layer >> It converts each word ID into a dense vector representation.

#Embedding will Captures semantic meaning
#Similar words → similar vectors
# Learns during training


In [298]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding,LSTM,Dense,Dropout

In [299]:
model=Sequential()
model.add(Embedding(input_dim=max_words, output_dim=128)) # it is max feture size= input_dimenstion.
model.add(LSTM(128,return_sequences=False)) # o/p dim 128 will same as lstm 128 unit of lstm 
model.add(Dropout(0.5))
model.add(Dense(1,activation='sigmoid'))


In [300]:
model.compile(
    loss='binary_crossentropy',
    optimizer='adam',
    metrics=['accuracy']
)

In [301]:
history =model.fit(
         X_train,
         y_train,
         epochs=20,
         validation_data=(X_test,y_test)
)

Epoch 1/20


35/35 ━━━━━━━━━━━━━━━━━━━━ 14s 229ms/step - accuracy: 0.5896 - loss: 0.6638 - val_accuracy: 0.5950 - val_loss: 0.6490
Epoch 2/20
35/35 ━━━━━━━━━━━━━━━━━━━━ 7s 199ms/step - accuracy: 0.7401 - loss: 0.5473 - val_accuracy: 0.7491 - val_loss: 0.5010
Epoch 3/20
35/35 ━━━━━━━━━━━━━━━━━━━━ 7s 187ms/step - accuracy: 0.8898 - loss: 0.3344 - val_accuracy: 0.7921 - val_loss: 0.4829
Epoch 4/20
35/35 ━━━━━━━━━━━━━━━━━━━━ 7s 187ms/step - accuracy: 0.9471 - loss: 0.1786 - val_accuracy: 0.8100 - val_loss: 0.4361
Epoch 5/20
35/35 ━━━━━━━━━━━━━━━━━━━━ 10s 188ms/step - accuracy: 0.9633 - loss: 0.1106 - val_accuracy: 0.8029 - val_loss: 0.5447
Epoch 6/20
35/35 ━━━━━━━━━━━━━━━━━━━━ 11s 200ms/step - accuracy: 0.9749 - loss: 0.0771 - val_accuracy: 0.8136 - val_loss: 0.5766
Epoch 7/20
35/35 ━━━━━━━━━━━━━━━━━━━━ 7s 192ms/step - accuracy: 0.9839 - loss: 0.0561 - val_accuracy: 0.8029 - val_loss: 0.6732
Epoch 8/20
35/35 ━━━━━━━━━━━━━━━━━━━━ 7s 195ms/step - accuracy: 0.9910 - loss: 0.0411 - val_accuracy: 0.7993 - v

In [302]:
# so we got val_accuracy =83 % and accuracy is 99%.

In [303]:
#Step 4. Check Test accuracy :

In [304]:
loss,accuracy= model.evaluate(X_test,y_test)
print("Test Accuracy:",accuracy)

9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 79ms/step - accuracy: 0.7957 - loss: 1.1608
Test Accuracy: 0.7956989407539368


In [305]:
# we dont have long data model ,so now we train new model on whole data not only train data for better accurcy:
history =model.fit(
         X,
         y,
         epochs=27,
         batch_size=32)

Epoch 1/27


44/44 ━━━━━━━━━━━━━━━━━━━━ 10s 212ms/step - accuracy: 0.9491 - loss: 0.1825
Epoch 2/27
44/44 ━━━━━━━━━━━━━━━━━━━━ 8s 178ms/step - accuracy: 0.9828 - loss: 0.0645
Epoch 3/27
44/44 ━━━━━━━━━━━━━━━━━━━━ 9s 206ms/step - accuracy: 0.9900 - loss: 0.0331
Epoch 4/27
44/44 ━━━━━━━━━━━━━━━━━━━━ 8s 187ms/step - accuracy: 0.9957 - loss: 0.0202
Epoch 5/27
44/44 ━━━━━━━━━━━━━━━━━━━━ 8s 175ms/step - accuracy: 0.9964 - loss: 0.0152
Epoch 6/27
44/44 ━━━━━━━━━━━━━━━━━━━━ 11s 187ms/step - accuracy: 0.9950 - loss: 0.0156
Epoch 7/27
44/44 ━━━━━━━━━━━━━━━━━━━━ 10s 177ms/step - accuracy: 0.9950 - loss: 0.0145
Epoch 8/27
44/44 ━━━━━━━━━━━━━━━━━━━━ 8s 170ms/step - accuracy: 0.9957 - loss: 0.0120
Epoch 9/27
44/44 ━━━━━━━━━━━━━━━━━━━━ 8s 184ms/step - accuracy: 0.9950 - loss: 0.0112
Epoch 10/27
44/44 ━━━━━━━━━━━━━━━━━━━━ 10s 178ms/step - accuracy: 0.9978 - loss: 0.0102
Epoch 11/27
44/44 ━━━━━━━━━━━━━━━━━━━━ 9s 203ms/step - accuracy: 0.9986 - loss: 0.0080
Epoch 12/27
44/44 ━━━━━━━━━━━━━━━━━━━━ 9s 196ms/step - accu

In [306]:
# Step 5. Predict the model: and check Metrics :

In [307]:
y_pred=model.predict(X_test)

9/9 ━━━━━━━━━━━━━━━━━━━━ 2s 153ms/step


In [308]:
y_pred1=[ 1 if i>0.5 else 0 for i in y_pred]

In [309]:
# check metrics:
from sklearn.metrics import confusion_matrix,classification_report


In [310]:
confusion_matrix(y_test,y_pred1)

array([[129,   0],
       [  0, 150]])

In [311]:
print(classification_report(y_test,y_pred1))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00       129
           1       1.00      1.00      1.00       150

    accuracy                           1.00       279
   macro avg       1.00      1.00      1.00       279
weighted avg       1.00      1.00      1.00       279



In [312]:
# step 6. Save the model :

In [313]:
model.save('Lstm_resturant_review_pred.keras')

In [314]:
# Step 6. Predict the new Review :

In [315]:
# By Using LSTM Predict.

In [316]:
a = 'good taste'

In [317]:
def predict_text(text):
    text = text.lower()
    seq = tk.texts_to_sequences([text])
    padded= pad_sequences(seq,maxlen=max_len)
    pred = model.predict(padded)[0][0]

    if pred > 0.5:
        return f"positive ({pred:.2f})"
    else:
        return f"Negative ({pred:.2f})"

In [326]:
# then call the pred fun:

predict_text('bad food ')

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 205ms/step


'Negative (0.05)'

In [327]:
# good taste >> 1
# bad food >> 0
# not bad >> 1
# not good >> 0